export const SET_IMAGE_LINK = 'SET_IMAGE_LINK';

export const FACE_DETECTION_PENDING = 'FACE_DETECTION_PENDING';
export const FACE_DETECTION_SUCCESS = 'FACE_DETECTION_SUCCESS';
export const FACE_DETECT_FAILED = 'FACE_DETECT_FAILED';
